### PR TITLE
Proposal: Add window activation/deactivation events

### PR DESCRIPTION
**Pull request by cute-jumper**
Companion change on the server side: https://github.com/cute-jumper/projector-server/tree/window-activation-deactivation. If this proposal is good, I will continue to create a PR for `projector-server`.

Set `window.onblur` and `window.onfocus` so that when users switch to another tab or switch back to the projector tab, `WINDOW_DEACTIVATED` or `WINDOW_ACTIVATED` (`WindowEvent`) will be posted on the server side. Currently, we post the event for all the windows visible in the current tab. Not quite sure about the side effect of doing this, but this seems to work fine with IntelliJ.

NOTE: IntelliJ relies on the `WINDOW_DEACTIVATED` to save changes to disk & `WINDOW_ACTIVATED` to load external file system changes.

### CODE REVIEW

**Comment by SerVB** [comment]
It's a great change! Am I right that it will address [PRJ-157](https://youtrack.jetbrains.com/issue/PRJ-157) and allow autosave in IDEs work properly?

If you decide to continue it, please also update the protocol version ID as the failing test says.

**Comment by cute-jumper** [comment]
@SerVB Thanks for the review. I updated the protocol version per the failing test.

> Am I right that it will address PRJ-157 and allow autosave in IDEs work properly?

Yep, I think so.

**Comment by zhipengzuo** [comment]
> @aauren Yes, it works for that case as well. Feel free to grab this PR & the server side change https://github.com/cute-jumper/projector-server/tree/window-activation-deactivation to build a local projector server and test it.

good job .will you merge it to solve https://youtrack.jetbrains.com/issue/PRJ-157 ?

**Comment by cute-jumper** [comment]
@SerVB Will you be interested in merging the PR? I'm happy to rebase the change onto the latest master if we would like to move forward

**Comment by SerVB** [comment]
@cute-jumper, yes, it's still a great change that solves our opened issues :) I was waiting for you to open a paired PR in projector-server and we can merge it (probably not instantly, but after a release – just to delay the change in the protocol for the next time).

**Comment by cute-jumper** [comment]
Messed up the history. Open a new one instead: https://github.com/JetBrains/projector-client/pull/85

**Pull request closed without merging**
